# Testing Scraper on GDELT Data

### Imports and Notebook Settings

In [56]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [57]:
import os 
import re
from pathlib import Path

In [58]:
import pandas as pd
import numpy as np 

import matplotlib.pyplot as plt
# import seaborn as sns 
import plotly.express as px
import pprint

In [59]:
import requests
import trafilatura
from bs4 import BeautifulSoup
from datetime import datetime, timezone

In [60]:
ROOT = Path.cwd().parent

In [61]:
style_path = ( ROOT 
              / 'notebooks' 
              / 'styler.mplstyle'
              )
plt.style.use(style_path)

In [62]:
data_path = (ROOT 
             / 'data'
             / 'silver'
             / 'source=gdelt'
             /  'records.parquet'
             )

In [63]:
df = pd.read_parquet(data_path)

In [64]:
df.drop(columns=['raw'])

,record_id,source,source_type,title,text,published_at,retrieved_at,url,region,categories,metadata
0,20260420130000-579,gdelt,api,'The absolute edge of precedent': FERC prepares to take on data centers,,2026-04-20T13:00:00+00:00,2026-06-18T14:49:51.869112+00:00,https://www.eenews.net/articles/the-absolute-edge-of-precedent-ferc-prepares-to-take-on-data-centers/,"2#NEW JERSEY, UNITED STATES#US#USNJ#40.314#-74.5089#NJ","[EPU_POLICY, EPU_POLICY_WHITE_HOUSE, TAX_FNCACT, TAX_FNCACT_REGULATORS, EPU_POLICY_REGULATORY, PROTEST, STRIKE, ECON_ELECTRICALDEMAND, TAX_FNCACT_SECRETARY, ECON_ELECTRICALGRID, TECH_SUPERCOMPUTING, USPEC_POLICY1, EPU_ECONOMY, EPU_ECONOMY_HISTORIC, LEADER, TAX_FNCACT_PRESIDENT, USPEC_POLITICS_GENERAL1, TRIAL, TAX_FNCACT_ATTORNEY, LEGISLATION, EPU_POLICY_LAW, EPU_CATS_MIGRATION_FEAR_FEAR, WB_696_PUBLIC_SECTOR_MANAGEMENT, WB_831_GOVERNANCE, WB_1921_PRIVATE_SECTOR_DEVELOPMENT, WB_346_COMPETITIVE_INDUSTRIES, WB_818_INDUSTRY_POLICY_AND_REAL_SECTORS, WB_1281_MANUFACTURING, TAX_ETHNICITY, TAX_ETHNICITY_AMERICAN, SCIENCE, SOC_INNOVATION, TAX_FNCACT_REGULATOR, TAX_FNCACT_COMMISSIONERS, TAX_FNCACT_SPOKESPERSON, EPU_POLICY_POLICY, ELECTION, WB_137_WATER, TAX_ECON_PRICE, ECON_COST_OF_LIVING, ECON_ELECTRICALPRICE, DEMOCRACY, TAX_POLITICAL_PARTY, TAX_POLITICAL_PARTY_REPUBLICAN, EPU_POLICY_SPENDING, WB_678_DIGITAL_GOVERNMENT, WB_2944_SERVERS, WB_671_STORAGE_MANAGEMENT, WB_667_ICT_INFRASTRUCTURE, WB_672_NETWORK_MANAGEMENT, WB_133_INFORMATION_AND_COMMUNICATION_TECHNOLOGIES, WB_675_WEB_FARM, WB_674_SHARED_INFRASTRUCTURE, TAX_FNCACT_DIRECTOR, EDUCATION, SOC_POINTSOFINTEREST, SOC_POINTSOFINTEREST_SCHOOL, TAX_FNCACT_POLITICIANS, BAN, TAX_FNCACT_REPRESENTATIVES, TAX_FNCACT_POLITICO, UNGP_POLITICAL_FREEDOMS, ECON_ELECTRICALGENERATION, WB_508_POWER_SYSTEMS, WB_507_ENERGY_AND_EXTRACTIVES, ENV_COAL, UNGP_FORESTS_RIVERS_OCEANS, WB_509_NUCLEAR_ENERGY, ENV_SOLAR, WB_525_RENEWABLE_ENERGY, WB_528_SOLAR_ENERGY, TAX_FNCACT_GOVERNORS, WB_2048_COMPENSATION_CAREERS_AND_INCENTIVES, WB_723_PUBLIC_ADMINISTRATION, WB_724_HUMAN_RESOURCES_FOR_PUBLIC_SECTOR, WB_698_TRADE, WB_840_JUSTICE, TAX_FNCACT_PROFESSOR, EPU_POLICY_REGULATION, EPU_CATS_REGULATION, TAX_FNCACT_CEO, CRISISLEX_T11_UPDATESSYMPATHY, TAX_FNCACT_EXECUTIVE, TAX_FNCACT_OPERATOR, AFFECT, TAX_FNCACT_EXECUTIVE_DIRECTOR, ALLIANCE, WB_694_BROADCAST_AND_MEDIA, MEDIA_SOCIAL, WB_652_ICT_APPLICATIONS, WB_662_SOCIAL_MEDIA, WB_658_ENTERPRISE_APPLICATIONS]","{'source_common_name': 'eenews.net', 'gdelt_timestamp': '20260420130000', 'organizations': ['american electric power', 'edison electric institute', 'yale law school', 'dominion energy', 'energy law', 'electricity consumers resource council', 'william mary law school', 'energy department', 'energy regulatory commission', 'microsoft', 'oracle', 'national association of regulatory utility commissioners', 'white house', 'google', 'christie', 'electricity customer alliance', 'entergy', 'energy bar association'], 'persons': ['chris wright', 'vinson elkins', 'mark christie', 'laura swett', 'glenn youngkin', 'donald trump', 'karen onaran', 'justice brandeis', 'josh shapiro', 'vince duane', 'jeff dennis', 'joshua macey'], 'locations': ['2#NEW JERSEY, UNITED STATES#US#USNJ#40.314#-74.5089#NJ', 'GEORGIA, UNITED STATES', '2#TEXAS, UNITED STATES#US#USTX#31.106#-97.6475#TX', 'TEXAS, UNITED STATES', '2#VIRGINIA, UNITED STATES#US#USVA#37.768#-78.2057#VA', 'US', '2#GEORGIA, UNITED STATES#US#USGA#32.9866#-83.6487#GA', '2#OHIO, UNITED STATES#US#USOH#40.3736#-82.7755#OH', '3#WHITE HOUSE, DISTRICT OF COLUMBIA, UNITED STATES#US#USDC#38.8951#-77.0364#531871', 'USNJ', 'USPA', 'USGA', '1#UNITED STATES#US#US#39.828175#-98.5795#US', 'OHIO, UNITED STATES', 'USDC', 'USOH', 'NEW JERSEY, UNITED STATES', '2#PENNSYLVANIA, UNITED STATES#US#USPA#40.5773#-77.264#PA', 'PENNSYLVANIA, UNITED STATES', 'USIN', 'USTX', 'UNITED STATES', 'VIRGINIA, UNITED STATES', 'WHITE HOUSE, DISTRICT OF COLUMBIA, UNITED STATES', '2#INDIANA, UNITED STATES#US#USIN#39.8647#-86.2604#IN', 'INDIANA, UNITED STATES', 'USVA'], 'tone': '0.332541567695962,2.8978622327791,2.56532066508314,5.46318289786223,23.8479809976247,0.237529691211401,1959', 'theme_match': True, 'organization_match': True, 'location_match': False, 'filter_match_count': 2}"
1,20260420143000-252,gdelt,api,American Electric Power (NASDAQ:AEP) Price Target Raised to $144.00 at Wells Fargo & Company,,2026-04-20T14:30:00+00:00,2026-06-18T14:49:51.869282+00:00,https://www.themarketsdaily.com/2026/04/20/american-electric-power-nasdaqaep-price-target-raised-to-144-00-at-wells-fargo-company.html,"2#OHIO, UNITED STATES#US#USOH#40.3736#-82.7755#OH","[TAX_ETHNICITY, TAX_ETHNICITY_AMERICAN, ECON_STOCKMARKET, TAX_ECON_PRICE, TAX_FNCACT, TAX_FNCACT_ANALYSTS, TAX_DISEASE, TAX_DISEASE_OVERWEIGHT, WB_1406_DISEASES, WB_1435_OBESITY, WB_621_HEALTH_NUTRITION_AND_POPULATION, WB_1427_NON_COMMUNICABLE_DISEASE_AND_INJURY, TAX_FNCACT_ANALYST, EPU_ECONOMY_HISTORIC, TAX_FNCACT_INSIDERS, TAX_FNCACT_EXECUTIVE, LEADER, TAX_FNCACT_PRESIDENT, USPEC_POLITICS_GENERAL1, TAX_FNCACT_VICE_PRESIDENT, TAX_FNCACT_EXECUTIVE_VICE_PRESIDENT, WB_698_TRADE, EPU_CATS_REGULATION, EPU_CATS_FINANCIAL_REGULATION, TAX_FNCACT_OFFICIAL, TAX_ETHNICITY_CZECH, TAX_WORLDLANGUAGES, TAX_WORLDLANGUAGES_CZECH, RETIREMENT, ECON_ELECTRICALGENERATION, UNGP_FORESTS_RIVERS_OCEANS, WB_1921_PRIVATE_SECTOR_DEVELOPMENT, WB_346_COMPETITIVE_INDUSTRIES, WB_1226_INDUSTRIAL_CLUSTERS_AND_VALUE_CHAINS, ENV_NATURALGAS, ENV_HYDRO, WB_507_ENERGY_AND_EXTRACTIVES, WB_525_RENEWABLE_ENERGY, WB_527_HYDROPOWER]","{'source_common_name': 'themarketsdaily.com', 'gdelt_timestamp': '20260420143000', 'organizations': ['community financial services group', 'american electric power', 'american electric power company profile', 'national pension service', 'czech national bank', 'jefferies financial group', 'wells fargo company', 'jpmorgan chase co', 'benjamin edwards inc', 'united states'], 'persons': ['kelly j ferneau', 'phillip r ulrich'], 'locations': ['2#OHIO, UNITED STATES#US#USOH#40.3736#-82.7755#OH', 'COLUMBUS, OHIO, UNITED STATES', 'EZ', '1#UNITED STATES#US#US#39.828175#-98.5795#US', 'UNITED STATES', 'CZECH REPUBLIC', '1#CZECH REPUBLIC#EZ#EZ#49.75#15#EZ', 'OHIO, UNITED STATES', '3#COLUMBUS, OHIO, UNITED STATES#US#USOH#39.9612#-82.9988#1080996', 'US', 'USOH'], 'tone': '1.16696588868941,1.43626570915619,0.269299820466786,1.70556552962298,22.5314183123878,0,1024', 'theme_match': True, 'organization_match': True, 'location_match': False, 'filter_match_count': 2}"
2,20260420164500-1460,gdelt,api,Wreck knocks out power to hundreds in Orange overnight,,2026-04-20T16:45:00+00:00,2026-06-18T14:49:51.869370+00:00,https://www.12newsnow.com/article/traffic/wreck-knocks-out-power-to-hundreds-in-orange/502-24e43403-5c49-4c2a-948b-bfbd4ca8cbdf,"3#WEST PARK, TEXAS, UNITED STATES#US#USTX#26.2978#-98.1667#2029942","[MANMADE_DISASTER, MANMADE_DISASTER_WITHOUT_POWER, POWER_OUTAGE, TAX_FNCACT, TAX_FNCACT_AUTHORITIES, CRISISLEX_CRISISLEXREC, EPU_POLICY, EPU_POLICY_AUTHORITIES, TAX_FNCACT_DRIVER, TAX_ETHNICITY, TAX_ETHNICITY_POLES, MANMADE_DISASTER_KNOCKED_OUT_POWER, GENERAL_HEALTH, MEDICAL, CRISISLEX_C03_WELLBEING_HEALTH, WB_635_PUBLIC_HEALTH, WB_2165_HEALTH_EMERGENCIES, WB_621_HEALTH_NUTRITION_AND_POPULATION, WB_1324_EMERGENCY_MEDICAL_SERVICES, TRAFFIC]","{'source_common_name': '12newsnow.com', 'gdelt_timestamp': '20260420164500', 'organizations': ['dodge', 'entergy'], 'persons': ['nan'], 'locations': ['3#WEST PARK, TEXAS, UNITED STATES#US#USTX#26.2978#-98.1667#2029942', '2#TEXAS, UNITED STATES#US#USTX#31.106#-97.6475#TX', 'WEST PARK, TEXAS, UNITED STATES', 'USTX', 'TEXAS, UNITED STATES', 'US'], 'tone': '-4.93827160493827,0,4.93827160493827,4.93827160493827,26.5432098765432,1.23456790123457,153', 'theme_match': True, 'organization_match': True, 'location_match': False, 'filter_match_count': 2}"
3,20260420181500-907,gdelt,api,Michigan Feared Cheboygan Dam Danger Before Rains Pushed it to Brink,,2026-04-20T18:15:00+00:00,2026-06-18T14:49:51.869457+00:00,https://www.insurancejournal.com/news/midwest/2026/04/20/866603.htm,"3#-HARBOR SPRINGS, MICHIGAN, UNITED STATES#US#USMI#45.4317#-84.992#627758","[TAX_FNCACT, TAX_FNCACT_OFFICIALS, TAX_FNCACT_FEDERAL_OFFICIALS, MANMADE_DISASTER_IMPLIED, NATURAL_DISASTER, NATURAL_DISASTER_FLOODWATERS, CRISISLEX_CRISISLEXREC, UNGP_FORESTS_RIVERS_OCEANS, CRISISLEX_T04_INFRASTRUCTURE, SANITATION, WB_137_WATER, URBAN, TAX_FNCACT_COMMISSIONER, LEADER, TAX_FNCACT_MAYOR, EPU_POLICY, EPU_POLICY_REGULATORY, EPU_ECONOMY_HISTORIC, MARITIME_INCIDENT, MARITIME, GOV_LOCALGOV, TAX_FNCACT_SHERIFF, CRISISLEX_C07_SAFETY, TAX_ECON_PRICE, ENV_HYDRO, WB_507_ENERGY_AND_EXTRACTIVES, WB_525_RENEWABLE_ENERGY, WB_527_HYDROPOWER, WB_161_DAMS_AND_RESERVOIRS, WB_141_WATER_RESOURCES_MANAGEMENT, WB_1000_WATER_MANAGEMENT_STRUCTURES, AFFECT, WB_1921_PRIVATE_SECTOR_DEVELOPMENT, WB_405_BUSINESS_CLIMATE, WB_2531_INSPECTIONS_LICENSING_AND_PERMITS, WB_2530_BUSINESS_ENVIRONMENT, NATURAL_DISASTER_FLOOD, CRISISLEX_C04_LOGISTICS_TRANSPORT, NATURAL_DISASTER_FLOODING, CRISISLEX_C06_WATER_SANITATION, GENERAL_HEALTH, MEDICAL, WB_1383_HEALTH_MANAGEMENT_AND_ADMINISTRATION, WB_621_HEALTH_NUTRITION_AND_POPULATION, DISASTER_FIRE, CRISISLEX_T01_CAUTION_ADVICE, NATURAL_DISASTER_DAM_FAILURE, MANMADE_DISASTER, MANMADE_DISASTER_DAM_FAILURE, TAX_FNCACT_SPOKESPERSON, WB_696_PUBLIC_SECTOR_MANAGEMENT, WB_831_GOVERNANCE, WB_838_PUBLIC_ACCOUNTABILITY_MECHANISMS, CRISISLEX_O02_RESPONSEAGENCIESATCRISIS, DELAY, USPEC_UNCERTAINTY1, TAX_FNCACT_LEGISLATORS, WB_566_ENVIRONMENT_AND_NATURAL_RESOURCES, WB_901_ENVIRONMENTAL_SAFEGUARDS, WB_1386_DAM_SAFETY, TAX_WORLDLANGUAGES, TAX_WORLDLANGUAGES_HURON, ENV_WATERWAYS, WB_1805_WATERWAYS, WB_135_TRANSPORT, WB_1803_TRANSPORT_INFRASTRUCTURE, PROTEST, NEGOTIATIONS, WB_2670_JOBS, WB_1467_EDUCATION_FOR_ALL, WB_470_EDUCATION, WB_2131_EMPLOYABILITY_SKILLS_AND_JOBS, WB_1484_EDUCATION_SKILLS_DEVELOPMENT_AND_LABOR_MARKET, TAX_FNCACT_REGULATORS, SLFID_NATURAL_RESOURCES, WB_471_ECONOMIC_GROWTH, WB_1078_DETERMINANTS_OF_GROWTH, WB_1079_COMMODITIES_AND_RESOURCES, CLOSURE, WATER_SECURITY, NATURAL_DISASTER_WATER_LEVEL, WB_2769_JOBS_STRATEGIES, WB_2788_LABOR_MARKET_INSTITUTIONS_AND_POLICIES, WB_2802_WORKING_CONDITIONS, TRIAL, TAX_FNCACT_LAWYER, TAX_FNCACT_BUYER, TAX_FNCACT_MECHANIC, WB_427_WATER_ALLOCATION_AND_WATER_ECONOMICS, WB_1064_WATER_DEMAND_MANAGEMENT, NATURAL_DISASTER_FLOODWATER, EVACUATION, CRISISLEX_T09_DISPLACEDRELOCATEDEVACUATED, TAX_FNCACT_WORKERS, SECURITY_SERVICES, TAX_FNCACT_POLICE, TAX_MILITARY_TITLE, TAX_MILITARY_TITLE_COMMANDER, TAX_FNCACT_COMMANDER, TAX_WORLDLANGUAGES_LANGE, ...]","{'source_common_name': 'insurancejournal.com', 'gdelt_timestamp': '20260420181500', 'organizations': ['hydromine cheboygan', 'hom paper', 'associated press', 'great lakes tissue company', 'michigan department of environment', 'procter gamble', 'michigan state police', 'energy regulatory commission', 'department of natural resources', 'consumers energy', 'health administration'], 'persons': ['tyler tennent', 'celeste miller', 'gretchen whitmer', 'richard sangster', 'roy davis', 'cheboygan commons', 'bruce straub', 'todd ross', 'thomas homco', 'sharen lange', 'josef greenberg', 'john damoose', 'ed golder'], 'locations': ['3#-HARBOR SPRINGS, MICHIGAN, UNITED STATES#US#USMI#45.4317#-84.992#627758', '3#EATON RAPIDS, MICHIGAN, UNITED STATES#US#USMI#42.5092#-84.6558#625314', 'US', '3#LAKE HURON, MICHIGAN, UNITED STATES#US#USMI#44.948#-82.2611#1624619', 'CHEBOYGAN RIVER, MICHIGAN, UNITED STATES', 'WYOMING, UNITED STATES', '3#CHEBOYGAN COUNTY, MICHIGAN, UNITED STATES#US#USMI#45.45#-84.5006#1622958', 'GREAT LAKES, MICHIGAN, UNITED STATES', '3#CHEBOYGAN RIVER, MICHIGAN, UNITED STATES#US#USMI#45.6561#-84.4653#623137', 'MICHIGAN STATE POLICE, MICHIGAN, UNITED STATES', 'USMI', '3#MICHIGAN STATE POLICE, MICHIGAN, UNITED STATES#US#USMI#45.8411#-87.0189#2351894', '3#GREAT LAKES, MICHIGAN, UNITED STATES#US#USMI#45.6875#-84.4375#1783507', 'LAKE HURON, MICHIGAN, UNITED STATES', '-HARBOR SPRINGS, MICHIGAN, UNITED STATES', 'CHEBOYGAN COUNTY, MICHIGAN, UNITED STATES', 'MICHIGAN, UNITED STATES', 'HUBBARDSTON, MICHIGAN, UNITED STATES', '2#MICHIGAN, UNITED STATES#US#USMI#43.3504#-84.5603#MI', 'USWY', '3#HUBBARDSTON, MICHIGAN, UNITED STATES#US#USMI#43.0923#-84.8422#628745', 'EATON RAPIDS, MICHIGAN, UNITED STATES', '2#WYOMING, UNITED STATES#US#USWY#42.7475#-107.209#WY'], 'tone': '-2.30508474576271,1.89830508474576,4.20338983050847,6.10169491525424,23.728813559322,0.88135593220339,1383', 'theme_match': True, 'organization_match': True, 'location_match': False, 'filter_match_count': 2}"
4,20260420194500-1467,gdelt,api,Duke Energy: 100-Year Dividend Track Record — But $103B Capex Is Compressing The Credit Cushion - Duke En,,2026-04-20T19:45:00+00:00,2026-06-18T14:49:51.869517+00:00,https://www.benzinga.com/Opinion/26/04/51923036/duke-energy-100-year-dividend-track-record-but-103b-capex-is-compressing-the-credit-cushion,US,"[EPU_ECONOMY_HISTORIC, ECON_ELECTRICALGENERATION, ECON_NEWPOWERPLANT, WB_135_TRANSPORT, WB_1174_WAREHOUSING_AND_STORAGE, WB_793_TRANSPORT_AND_LOGISTICS_SERVICES, ENV_NATURALGAS, WB_539_OIL_AND_GAS_POLICY_STRATEGY_AND_INSTITUTIONS, WB_507_ENERGY_AND_EXTRACTIVES, WB_549_OIL_AND_GAS_SYSTEMS, WB_544_MID_AND_DOWNSTREAM_OIL_AND_GAS, WB_2291_OIL_AND_GAS_DISTRIBUTION, WB_551_GAS_TRANSPORTATION_STORAGE_AND_DISTRIBUTION, CRISISLEX_CRISISLEXREC, ECON_DEBT, WB_1104_MACROECONOMIC_VULNERABILITY_AND_DEBT, WB_450_DEBT, WB_1921_PRIVATE_SECTOR_DEVELOPMENT, WB_346_COMPETITIVE_INDUSTRIES, WB_818_INDUSTRY_POLICY_AND_REAL_SECTORS, WB_1281_MANUFACTURING, USPEC_POLICY1, EPU_POLICY, EPU_POLICY_SPENDING, EPU_POLICY_REGULATORY, WB_334_EQUITY_MARKETS, WB_1920_FINANCIAL_SECTOR_DEVELOPMENT, WB_332_CAPITAL_MARKETS, WB_1918_SECURITIES_MARKETS, TAX_ECON_PRICE]","{'source_common_name': 'benzinga.com', 'gdelt_timestamp': '20260420194500', 'organizations': ['brookfield infrastructure in duke energy florida', 'moody', 'duke energy'], 'persons': ['nan'], 'locations': ['US', '2#TENNESSEE, UNITED STATES#US#USTN#35.7449#-86.7489#TN', '2#FLORIDA, UNITED STATES#US#USFL#27.8333#-81.717#FL', '3#BROOKFIELD, TENNESSEE, UNITED STATES#US#USTN#35.007#-85.2452#1312612', 'USTN', 'FLORIDA, UNITED STATES', 'TENNESSEE, UNITED STATES', 'BROOKFIELD, TENNESSEE, UNITED STATES', 'USFL'], 'tone': '-1.48588410104012,2.37741456166419,3.86329866270431,6.2407132243685,22.2882615156018,0,604', 'theme_match': True, 'organization_match': True, 'location_match': False, 'filter_match_count': 2}"
...,...,...,...,...,...,...,...,...,...,...,...
309,20260521191500-1174,gdelt,api,"Google Pledges Power, Ratepayer Protections in $15B Missouri Data Center Expansion",,2026-05-21T19:15:00+00:00,2026-06-18T14:49:51.895095+00:00,https://www.powermag.com/google-pledges-power-ratepayer-protections-in-15b-missouri-data-center-expansion/,"2#MINNESOTA, UNITED STATES#US#USMN#45.7326#-93.9196#MN","[TAX_ECON_PRICE, ECON_ELECTRICALGENERATION, ECON_NEWPOWERPLANT, MANMADE_DISASTER_IMPLIED, USPEC_UNCERTAINTY1, CRISISLEX_C07_SAFETY, EPU_ECONOMY_HISTORIC, LEADER, TAX_FNCACT, TAX_FNCACT_GOVERNOR, WB_1920_FINANCIAL_SECTOR_DEVELOPMENT, WB_363_FINANCIAL_INCLUSION, WB_364_CONSUMER_PROTECTION, LEGISLATION, EPU_POLICY, EPU_POLICY_LAW, EPU_ECONOMY, SLFID_ECONOMIC_DEVELOPMENT, TAX_FNCACT_PRESIDENT, USPEC_POLITICS_GENERAL1, TAX_FNCACT_CHIEF, TAX_FNCACT_EXECUTIVE, TAX_FNCACT_CHIEF_EXECUTIVE, TAX_MILITARY_TITLE, TAX_MILITARY_TITLE_OFFICER, TAX_FNCACT_OFFICER, TAX_FNCACT_EXECUTIVE_OFFICER, TAX_FNCACT_CHIEF_EXECUTIVE_OFFICER, UNGP_FORESTS_RIVERS_OCEANS, ENV_NATURALGAS, WB_135_TRANSPORT, WB_1174_WAREHOUSING_AND_STORAGE, WB_793_TRANSPORT_AND_LOGISTICS_SERVICES, EPU_POLICY_REGULATORY, WB_1458_HEALTH_PROMOTION_AND_DISEASE_PREVENTION, WB_1462_WATER_SANITATION_AND_HYGIENE, WB_635_PUBLIC_HEALTH, WB_621_HEALTH_NUTRITION_AND_POPULATION, ENV_GEOTHERMAL, TAX_WORLDMAMMALS, TAX_WORLDMAMMALS_BEAR, USPEC_POLICY1, EPU_POLICY_REGULATION, EPU_CATS_REGULATION, CRISISLEX_T11_UPDATESSYMPATHY, ENV_SOLAR, KILL, ENV_HYDRO, WB_507_ENERGY_AND_EXTRACTIVES, WB_525_RENEWABLE_ENERGY, WB_527_HYDROPOWER, WB_137_WATER, WB_161_DAMS_AND_RESERVOIRS, WB_141_WATER_RESOURCES_MANAGEMENT, WB_1000_WATER_MANAGEMENT_STRUCTURES, CRISISLEX_T04_INFRASTRUCTURE, MEDIA_SOCIAL, TAX_WORLDLANGUAGES, TAX_WORLDLANGUAGES_KANSAS, WB_1467_EDUCATION_FOR_ALL, WB_2132_APPRENTICESHIP, WB_470_EDUCATION, WB_1484_EDUCATION_SKILLS_DEVELOPMENT_AND_LABOR_MARKET, WB_696_PUBLIC_SECTOR_MANAGEMENT, WB_831_GOVERNANCE, WB_841_JUSTICE_SYSTEM_ADMINISTRATION, WB_1922_GOVERNANCE_STRUCTURES, WB_840_JUSTICE, TRANSPARENCY, TAX_FNCACT_DEPUTY, TAX_FNCACT_DIRECTOR, TAX_FNCACT_LABORERS, PUBLIC_TRANSPORT, WB_856_WAGES, WB_1654_ACTIVE_LABOR_MARKET_POLICIES, WB_855_LABOR_MARKETS, WB_697_SOCIAL_PROTECTION_AND_LABOR, WB_2048_COMPENSATION_CAREERS_AND_INCENTIVES, WB_723_PUBLIC_ADMINISTRATION, WB_724_HUMAN_RESOURCES_FOR_PUBLIC_SECTOR, WB_698_TRADE, WB_151_IRRIGATION_AND_DRAINAGE, WB_140_AGRICULTURAL_WATER_MANAGEMENT, AGRICULTURE]","{'source_common_name': 'powermag.com', 'gdelt_timestamp': '20260521191500', 'organizations': ['form energy', 'nv energy', 'tennessee valley authority', 'ameren corporation', 'community commitments', 'nevada public utilities commission', 'power research institute epri dcflex', 'missouri public service commission', 'housing development programs', 'entergy arkansas', 'xcel energy', 'smart irrigation initiative', 'google', 'indiana utility regulatory commission', 'clean energy accelerator charge', 'microsoft', 'weatherization apprenticeship program', 'energy impact fund', 'google head of advanced energy', 'sierra club', 'missouri industrial energy consumers', 'contractors training center', 'amazon web services', 'fervo energy', 'community action corporation'], 'persons': ['martin j lyons jr', 'michael terrell', 'carla potts', 'mike kehoe', 'evergy metro'], 'locations': ['2#MINNESOTA, UNITED STATES#US#USMN#45.7326#-93.9196#MN', '2#ILLINOIS, UNITED STATES#US#USIL#40.3363#-89.0022#IL', 'NEVADA, UNITED STATES', '2#TEXAS, UNITED STATES#US#USTX#31.106#-97.6475#TX', '3#BIG HOLLOW, MISSOURI, UNITED STATES#US#USMO#36.6215#-93.2118#714168', 'WEST VIRGINIA, UNITED STATES', '3#NEW FLORENCE, MISSOURI, UNITED STATES#US#USMO#38.9103#-91.4482#729575', 'TEXAS, UNITED STATES', 'US', 'MISSOURI, UNITED STATES', '3#BROOKFIELD, PENNSYLVANIA, UNITED STATES#US#USPA#39.8532#-75.5966#1203160', 'MONTGOMERY COUNTY, MISSOURI, UNITED STATES', 'USMO', '2#MISSOURI, UNITED STATES#US#USMO#38.4623#-92.302#MO', 'USIL', 'USPA', 'USMI', 'USMN', 'BROOKFIELD, PENNSYLVANIA, UNITED STATES', 'USWV', '2#PENNSYLVANIA, UNITED STATES#US#USPA#40.5773#-77.264#PA', 'PENNSYLVANIA, UNITED STATES', 'MICHIGAN, UNITED STATES', '2#WEST VIRGINIA, UNITED STATES#US#USWV#38.468#-80.9696#WV', 'USIN', '2#MICHIGAN, UNITED STATES#US#USMI#43.3504#-84.5603#MI', 'USTX', 'USNV', '3#MONTGOMERY COUNTY, MISSOURI, UNITED STATES#US#USMO#38.9667#-91.4835#758524', 'BIG HOLLOW, MISSOURI, UNITED STATES', 'NEW FLORENCE, MISSOURI, UNITED STATES', 'PLATTE, MINNESOTA, UNITED STATES', '2#INDIANA, UNITED STATES#US#USIN#39.8647#-86.2604#IN', '3#PLATTE, MINNESOTA, UNITED STATES#US#USMN#46.1055#-94.0822#649542', '2#NEVADA, UNITED STATES#US#USNV#38.4199#-117.122#NV', 'MINNESOTA, UNITED STATES', 'ILLINOIS, UNITED STATES', 'INDIANA, UNITED STATES'], 'tone': '2.31135282121006,3.60299116247451,1.29163834126445,4.89462950373895,21.4140040788579,0.475866757307954,1336', 'theme_match': True, 'organization_match': True, 'location_match': False, 'filter_match_count': 2}"

In [65]:
for i in df['title'].head(30):
    print(i)

'The absolute edge of precedent': FERC prepares to take on data centers
American Electric Power (NASDAQ:AEP) Price Target Raised to $144.00 at Wells Fargo & Company
Wreck knocks out power to hundreds in Orange overnight
Michigan Feared Cheboygan Dam Danger Before Rains Pushed it to Brink
Duke Energy: 100-Year Dividend Track Record — But $103B Capex Is Compressing The Credit Cushion - Duke En
Meta's $27 Billion Data Center Places the Spotlight on Natural Gas Stocks
Xcel: power shutoff 'possible' Wednesday amid wildfire risk | Western Colorado
Analysts' Recent Ratings Updates for American Electric Power (AEP)
Truist Financial Begins Coverage on American Electric Power (NASDAQ:AEP)
Powering Reliability: Duke Energy lineworkers sharpen skills at Carolinas Lineman's regional rodeo
Consumers Energy installs new weather stations to improve storm response
Consumers Energy launches weather station network in five Michigan counties
Alliant Energy: New wind project moves forward in Minnesota
Consumers Energy installing 100 weather stations across Michigan
Consumers Energy adds Michigan weather stations to predict outages and speed restoration
Consumers Energy launches weather station network in five Michigan counties
Consumers Energy adds Michigan weather stations to predict outages and speed restoration
Consumers Energy: New weather stations will help restore power quicker, save customers money
Data centers' energy demand drives grid construction in Central Virginia
Advocates cite lack of transparency, rising costs as regulators fast-track second Meta data center
'Growth pays for growth': Entergy's Fair Share Plus model to save Louisiana customers $2.8 billion | Sponsored: Entergy
Advocates cite lack of transparency, rising costs as regulators fast-track second Meta data center
'Growth pays for growth': Entergy's Fair Share Plus model to save Louisiana customers $2.8 billion | Sponsored: Entergy Louisiana
Transco Pipeline Project Faces Legal Challenge - Inside Climate News
Consumers Energy aims to speed up power restoration time, save $1M annually through new weather stations
Minnesota's energy system faces headwinds
Xcel Energy hoping to get wind turbines operational at Courtenay Wind Farm
Entergy (NYSE:ETR) Upgraded to Strong-Buy at Truist Financial
Data centers' energy demand drives grid construction in Central Virginia
Advocates cite lack of transparency, rising costs as regulators fast-track second Meta data center

In [83]:
import nest_asyncio
nest_asyncio.apply()

In [90]:
from datetime import datetime, timezone
import json

import aiohttp
import trafilatura
from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeoutError


def categorize_status(status: int | None) -> str:
    if status == 403:
        return "forbidden"
    if status == 404:
        return "not_found"
    if status == 429:
        return "rate_limited"
    if status is not None and 500 <= status < 600:
        return "server_error"
    if status is not None:
        return "http_error"
    return "unknown"


async def fetch_html(
    session: aiohttp.ClientSession,
    url: str,
    timeout: int = 15,
) -> dict:
    try:
        async with session.get(url, timeout=timeout) as response:
            text = await response.text(errors="ignore")

            if response.status >= 400:
                return {
                    "success": False,
                    "html": None,
                    "status_code": response.status,
                    "error_type": categorize_status(response.status),
                    "error_message": f"HTTP {response.status}",
                    "method": "aiohttp",
                }

            return {
                "success": True,
                "html": text,
                "status_code": response.status,
                "error_type": None,
                "error_message": None,
                "method": "aiohttp",
            }

    except TimeoutError as exc:
        return {
            "success": False,
            "html": None,
            "status_code": None,
            "error_type": "timeout",
            "error_message": str(exc),
            "method": "aiohttp",
        }

    except aiohttp.ClientConnectionError as exc:
        return {
            "success": False,
            "html": None,
            "status_code": None,
            "error_type": "connection_error",
            "error_message": str(exc),
            "method": "aiohttp",
        }

    except Exception as exc:
        return {
            "success": False,
            "html": None,
            "status_code": None,
            "error_type": "unknown",
            "error_message": str(exc),
            "method": "aiohttp",
        }


async def fetch_html_with_playwright(
    url: str,
    timeout: int = 30000,
) -> dict:
    try:
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)

            page = await browser.new_page(
                user_agent=(
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/137.0.0.0 Safari/537.36"
                )
            )

            response = await page.goto(
                url,
                wait_until="networkidle",
                timeout=timeout,
            )

            html = await page.content()
            status_code = response.status if response else None

            await browser.close()

        return {
            "success": True,
            "html": html,
            "status_code": status_code,
            "error_type": None,
            "error_message": None,
            "method": "playwright",
        }

    except PlaywrightTimeoutError as exc:
        return {
            "success": False,
            "html": None,
            "status_code": None,
            "error_type": "playwright_timeout",
            "error_message": str(exc),
            "method": "playwright",
        }

    except Exception as exc:
        return {
            "success": False,
            "html": None,
            "status_code": None,
            "error_type": "playwright_error",
            "error_message": str(exc),
            "method": "playwright",
        }


def extract_with_trafilatura(
    html: str,
    url: str,
    extractor: str,
) -> dict:
    result = trafilatura.extract(
        html,
        url=url,
        output_format="json",
        with_metadata=True,
        include_comments=False,
        include_tables=False,
    )

    if result is None:
        return {
            "success": False,
            "extractor": extractor,
            "title": None,
            "author": None,
            "date": None,
            "text": "",
            "error_type": "parse_failed",
            "error_message": "trafilatura returned None",
        }

    parsed = json.loads(result)
    text = parsed.get("text", "") or ""

    return {
        "success": True,
        "extractor": extractor,
        "title": parsed.get("title"),
        "author": parsed.get("author"),
        "date": parsed.get("date"),
        "text": text,
        "error_type": None,
        "error_message": None,
    }


async def scrape_article(
    session: aiohttp.ClientSession,
    url: str,
) -> dict:
    retrieved_at = datetime.now(timezone.utc).isoformat()

    fetch_result = await fetch_html(session, url)

    if (
        not fetch_result["success"]
        and fetch_result["error_type"] == "forbidden"
    ):
        fetch_result = await fetch_html_with_playwright(url)

    if not fetch_result["success"]:
        return {
            "success": False,
            "url": url,
            "status_code": fetch_result["status_code"],
            "error_type": fetch_result["error_type"],
            "error_message": fetch_result["error_message"],
            "fetch_method": fetch_result["method"],
            "extractor": None,
            "title": None,
            "author": None,
            "date": None,
            "text": "",
            "text_length": 0,
            "retrieved_at": retrieved_at,
        }

    extracted = extract_with_trafilatura(
        html=fetch_result["html"],
        url=url,
        extractor=f"trafilatura_after_{fetch_result['method']}",
    )

    return {
        "success": extracted["success"],
        "url": url,
        "status_code": fetch_result["status_code"],
        "error_type": extracted["error_type"],
        "error_message": extracted["error_message"],
        "fetch_method": fetch_result["method"],
        "extractor": extracted["extractor"],
        "title": extracted["title"],
        "author": extracted["author"],
        "date": extracted["date"],
        "text": extracted["text"],
        "text_length": len(extracted["text"]),
        "retrieved_at": retrieved_at,
    }

In [92]:
import pandas as pd
import aiohttp
import asyncio


async def scrape_urls(urls: list[str]) -> pd.DataFrame:
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/137.0.0.0 Safari/537.36"
        ),
        "Accept": "text/html,application/xhtml+xml",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://www.google.com/",
    }

    async with aiohttp.ClientSession(headers=headers) as session:
        results = [
            await scrape_article(session, url)
            for url in urls
        ]

    return pd.DataFrame(results)

In [101]:
urls = df["url"].dropna().head(100).tolist()

results_df = await scrape_urls(urls)

In [102]:
results_df[
    [
        "success",
        "url",
        "title",
        "date",
        "text_length",
        "extractor",
    ]
]

,success,url,title,date,text_length,extractor
0,True,https://www.eenews.net/articles/the-absolute-edge-of-precedent-ferc-prepares-to-take-on-data-centers/,‘The absolute edge of precedent’: FERC prepares to take on data centers,2026-04-20,13020,trafilatura_after_playwright
1,True,https://www.themarketsdaily.com/2026/04/20/american-electric-power-nasdaqaep-price-target-raised-to-144-00-at-wells-fargo-company.html,American Electric Power (NASDAQ:AEP) Price Target Raised to $144.00 at Wells Fargo & Company,2026-04-20,5933,trafilatura_after_aiohttp
2,True,https://www.12newsnow.com/article/traffic/wreck-knocks-out-power-to-hundreds-in-orange/502-24e43403-5c49-4c2a-948b-bfbd4ca8cbdf,Access Denied,None,300,trafilatura_after_playwright
3,True,https://www.insurancejournal.com/news/midwest/2026/04/20/866603.htm,Michigan Feared Cheboygan Dam Danger Before Rains Pushed it to Brink,2026-04-20,9263,trafilatura_after_aiohttp
4,True,https://www.benzinga.com/Opinion/26/04/51923036/duke-energy-100-year-dividend-track-record-but-103b-capex-is-compressing-the-credit-cushion,Duke Energy: 100-Year Dividend Track Record — But $103B Capex Is Compressing The Credit Cushion - Duke En,2026-04-20,4349,trafilatura_after_aiohttp
...,...,...,...,...,...,...
95,True,https://wbt.com/1644984/appeals-court-wrestles-with-nc-permit-for-mvp-pipeline/,Appeals Court wrestles with NC permit for MVP pipeline,2026-04-28,10223,trafilatura_after_aiohttp
96,False,https://wwmt.com/news/local/consumers-energy-deploys-500-crews-as-outages-peak-at-86000-most-back-by-tuesday-night-greg-salisbury-emmett-urbandale-pennfield-township-power-grid,None,None,0,None
97,True,https://wwmt.com/news/local/consumers-energy-deploys-500-crews-outages-peak-86000-restore-by-tuesday-night-greg-salisbury-emmett-urbandale-pennfield-township-power-grid,"Consumers Energy deploys 500 crews as outages peak at 86K, most restored by Tuesday night",2026-04-28,4071,trafilatura_after_aiohttp
98,True,https://www.fool.com/investing/2026/04/29/energy-stock-showdown-nextera-or-duke-energy-which/?source=iedfolrf0000001,Energy Stock Showdown: NextEra or Duke Energy -- Which One Wins Right Now? | The Motley Fool,2026-04-29,3437,trafilatura_after_aiohttp
99,True,https://wincountry.com/2026/04/29/921711/,"Crews continue to work on power restoration in hardest hit areas of Calhoun, Kalamazoo and St. Joseph counties",2026-04-29,1127,trafilatura_after_aiohttp

In [103]:
success_rate = results_df['success'].sum() / len(results_df)

print(f"{success_rate * 100}% of articles could be scraped")

90.0% of articles could be scraped

In [104]:
results_df["error_type"].value_counts(dropna=False)

error_type
None                  90
not_found              5
playwright_timeout     2
unknown                2
rate_limited           1
Name: count, dtype: int64

In [106]:
pd.set_option("display.max_colwidth", None)

results_df[
    ~results_df["success"]
][
    [
        "url",
        "status_code",
        "error_type",
        "error_message"
    ]
]

,url,status_code,error_type,error_message
7,https://www.dailypolitical.com/2026/04/21/analysts-recent-ratings-updates-for-american-electric-power-aep.html,404.0,not_found,HTTP 404
8,https://www.dailypolitical.com/2026/04/21/truist-financial-begins-coverage-on-american-electric-power-nasdaqaep.html,404.0,not_found,HTTP 404
30,https://www.erienewsnow.com/news/state/ohio-supreme-court-guts-submetering-business-said-to-drive-up-renters-electric-bills/article_7e99e81f-249c-5e71-80e5-5ba1c2aeb0b0.html,404.0,not_found,HTTP 404
44,https://www.powermag.com/duke-energys-robinson-nuclear-plant-gets-nrc-approval-to-operate-until-2050/,NaN,playwright_timeout,"Page.goto: Timeout 30000ms exceeded.\nCall log:\n - navigating to ""https://www.powermag.com/duke-energys-robinson-nuclear-plant-gets-nrc-approval-to-operate-until-2050/"", waiting until ""networkidle""\n"
56,https://kfiz.com/state-regulators-change-we-energies-data-center-rate-proposal-to-protect-customers/,NaN,playwright_timeout,"Page.goto: Timeout 30000ms exceeded.\nCall log:\n - navigating to ""https://kfiz.com/state-regulators-change-we-energies-data-center-rate-proposal-to-protect-customers/"", waiting until ""networkidle""\n"
59,https://finance.yahoo.com/markets/stocks/articles/southern-company-raises-dividend-2-141743349.html,NaN,unknown,"400, message='Got more than 8190 bytes when reading: b""connect-src \'self\' wss://*.finance.yahoo.com/ https://*.cdn.yimg.com https://*.oath.com https://*.ya..."".', url='https://finance.yahoo.com/markets/stocks/articles/southern-company-raises-dividend-2-141743349.html'"
60,https://finance.yahoo.com/sectors/energy/articles/nrc-renews-license-duke-energy-141832333.html,NaN,unknown,"400, message='Got more than 8190 bytes when reading: b""connect-src \'self\' wss://*.finance.yahoo.com/ https://*.cdn.yimg.com https://*.oath.com https://*.ya..."".', url='https://finance.yahoo.com/sectors/energy/articles/nrc-renews-license-duke-energy-141832333.html'"
89,https://www.yahoo.com/news/articles/stein-power-demand-rises-north-211542291.html,429.0,rate_limited,HTTP 429
94,https://www.wlfi.com/news/lafayette-cleanup-underway-after-storms-leave-hundreds-without-power/article_4efb86af-befd-4084-988b-cbaa6b004657.html,404.0,not_found,HTTP 404
96,https://wwmt.com/news/local/consumers-energy-deploys-500-crews-as-outages-peak-at-86000-most-back-by-tuesday-night-greg-salisbury-emmett-urbandale-pennfield-township-power-grid,404.0,not_found,HTTP 404

In [107]:
results_df.columns

Index(['success', 'url', 'status_code', 'error_type', 'error_message',
       'fetch_method', 'extractor', 'title', 'author', 'date', 'text',
       'text_length', 'retrieved_at'],
      dtype='object')